import { SafeAreaView, ScrollView, Text, TouchableOpacity, View } from "react-native";
import React from "react";
import { useRouter } from "expo-router";
import AsyncStorage from "@react-native-async-storage/async-storage";

const Disclaimer = () => {
    const router = useRouter();

    const handleAccept = async () => {
        await AsyncStorage.setItem("hasSeenDisclaimer", "true");
        router.replace("/");
    };

    return (
        <SafeAreaView style={{ flex: 1, backgroundColor: "white" }}>
            <ScrollView contentContainerStyle={{ padding: 24 }}>
                <View style={{ alignItems: "center", marginBottom: 24 }}>
                    <Text style={{ fontSize: 24, fontWeight: "700", color: "#111", textAlign: "center" }}>
                        About Market-House
                    </Text>
                </View>

                <Text style={{ fontSize: 20, fontWeight: "600", color: "#111", marginBottom: 10 }}>
                    Disclaimer:
                </Text>

                <Text style={{ fontSize: 16, color: "#333", marginBottom: 16, textAlign: "justify" }}>
                    The numbers and graphs presented by this app are estimates generated by our model based on user-provided inputs.
                    These projections are for informational purposes only and do not constitute financial advice.
                </Text>

                <Text style={{ fontSize: 16, color: "#333", fontWeight: "bold", marginBottom: 10, textAlign: "justify" }}>
                    This app compares the return on a stock market investment with the return on the same amount invested in real estate over the same period of time.
                </Text>

                <Text style={{ fontSize: 16, color: "#333", marginBottom: 16, textAlign: "justify" }}>
                    This app is designed to provide a comprehensive comparison between stock market and real estate investments over the same period.
                    Users can input detailed parameters for both types of investments to see how they would perform side by side.
                    For stock market investments, users can specify the initial investment amount, expected annual return rate, annual dividend yield, and transaction fees.
                    For real estate investments, users input the property purchase price, down payment, mortgage rate, mortgage term,
                    expected annual property appreciation rate, monthly rental income, vacancy rate, annual operating expenses, and selling costs.
                </Text>

                <Text style={{ fontSize: 16, color: "#333", marginBottom: 16, textAlign: "justify" }}>
                    The app then calculates key metrics for both investment types. For the stock market, it estimates the final value, dividend returns,
                    total value with dividends, and the net returns before capital gains tax and fees. For real estate, it estimates the mortgage amount,
                    monthly mortgage payment, total rental revenue, total operating costs, expected selling price, net selling price after mortgage balance,
                    and net returns before capital gains tax. The final output includes a side-by-side comparison, highlighting the differences in net returns
                    between the two investment strategies, offering users a clear view of which investment might be more lucrative given their specific inputs.
                </Text>

                <TouchableOpacity
                    onPress={handleAccept}
                    style={{
                        backgroundColor: "#007AFF",
                        paddingVertical: 14,
                        borderRadius: 8,
                        marginTop: 20,
                        alignItems: "center",
                    }}
                >
                    <Text style={{ color: "white", fontSize: 18, fontWeight: "600" }}>
                        I Understand
                    </Text>
                </TouchableOpacity>
            </ScrollView>
        </SafeAreaView>
    );
};

export default Disclaimer;
